title: Sergey Shmakov # Add a space after the period

logo: Me.png # Use a relative path to logo image 

description: Research scientist. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "phON0U--Ul0kfGMp5NCAtLGWvDwYfItH8eVC5srOPKg" # Verify ownership through Search Console  

email: sergey.shmakov@gmail.com # Allow visitors to contact you